### ISSUE TITLE
Multiple profiles

### ISSUE THREAD

**Issue by SilasK** [percyfal/slurm#2]
Hey @percyfal  Have you an Idea how to use multiple partitions, e.g. one for more memory_intensive jobs?

Ideally the users provide a yaml file with the profile definition:
```
 profiles:
     normal:
        max_min:6000
       max_mb:10000
     bigmem:
...
```
and the scheduler chooses which one is the best.

**Comment by percyfal** [comment]
Not really, no. This could also be a case where you use the resources keyword of a rule. Currently there is support for setting runtime, memory, and the number of threads. However, changing partitions (e.g. core vs node partitions) is not possible via this route.

**Comment by percyfal** [comment]
I just updated the slurm profile to include an advanced slurm submission script that takes the cluster-config file into account. I don't know what your cluster configuration looks like, but it is possible that there are features attributed to the different partitions. If so, you can specify a constraint in the cluster configuration file to enforce the selection of specific partitions when submitting jobs. See the README for details.
