### ISSUE TITLE
How to pass additional parameters to the  slurm-submit script?

### ISSUE THREAD

**Issue by SilasK** [percyfal/slurm#3]
I've seen you wrote a long list of arguments which can be given to the `slurm-submit.py` how can I pass them to the script?

I tried in the config.yaml
`time:600`

and it passed the 600 as target to the snakefile, which search for the file.

**Comment by SilasK** [comment]
@percyfal Have you seen my question?

**Comment by percyfal** [comment]
Hi, sorry for late reply; no, I hadn't seen your question and it seems missing in my mail. I think it'd be better if you post issues on the SnakemakeProfiles page.

Anyhow; I decided to model the submit script on the one in pbs-torque without actually having looked into the details of how to pass parameters from within snakemake. As you have noticed, it's not evident how to do so, and I'm afraid I don't have an answer at the moment.

**Comment by percyfal** [comment]
Rereading your issue description now makes me realize I didn't read it carefully enough. If you want to change running time for a rule, use the resources keyword, e.g:

`
rule foo:
    resources: runtime=600
`

Closing for now, but feel free to reopen if you want to discuss it further.
